In [1]:
import scanpy as sc
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

/wynton/group/gartner/zuzhi/.conda/envs/scenv/lib/python3.13/site-packages/louvain/__init__.py:54: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound


In [2]:
# print the time and date
from datetime import datetime
print("Current date and time: ", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

Current date and time:  2025-06-25 19:50:06


# cross_tissue_Eraslan

In [3]:
# load the adata object
adata_Eraslan = sc.read_h5ad('../data/cross_tissue_Eraslan/cross_tissue_Eraslan_final.h5ad')

In [4]:
adata_Eraslan.X[0:10,0:10].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.70614594, 0.70614594, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.4964045 , 0.        , 0.        , 1.0053275 ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.0142013 , 0.        , 1.0142013 , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.5509802 , 0.        , 1.0501379 , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.       

In [ ]:
adata_Eraslan
# batch_key = 'donor_id'
# state_key = 'cell_type'

AnnData object with n_obs × n_vars = 209126 × 2000
    obs: 'Sample ID_prep', 'assay_ontology_term_id', 'cell_type_ontology_term_id', 'disease_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'is_primary_data', 'organism_ontology_term_id', 'sex_ontology_term_id', 'tissue_ontology_term_id', 'n_genes', 'fpr', 'prep', 'individual', 'nGenes', 'nUMIs', 'PercentMito', 'PercentRibo', 'Age_bin', 'Sample ID', 'donor_id', 'Sample ID short', 'RIN score from PAXgene tissue Aliquot', 'RIN score from Frozen tissue Aliquot', 'Autolysis Score', 'Sample Ischemic Time (mins)', 'scrublet', 'scrublet_score', 'batch', 'n_counts', 'tissue-individual-prep', 'Broad cell type', 'Granular cell type', 'introns', 'junctions', 'exons', 'sense', 'antisense', 'intergenic', 'exon_ratio', 'intron_ratio', 'junction_ratio', 'log10_nUMIs', 'leiden', 'leiden_tissue', 'Tissue composition', 'Cell types level 2', 'Cell types level 3', 'Broad cell type numbers', 'Broad cell type (numbers)', 'channel', 'developme

----

# dkd_Wilson

In [8]:
# load the adata object
adata_Wilson = sc.read_h5ad('../data/dkd_Wilson/dkd_Wilson_final.h5ad')

In [9]:
adata_Wilson.X[0:10,0:10].toarray()

array([[0.       , 0.       , 0.       , 0.       , 0.       , 1.0986123,
        0.6931472, 0.       , 0.       , 0.       ],
       [0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
        0.       , 0.       , 0.       , 0.       ],
       [0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
        0.       , 0.       , 0.       , 0.       ],
       [0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
        0.6931472, 0.       , 0.       , 0.       ],
       [0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
        0.       , 0.       , 0.       , 0.       ],
       [0.       , 0.       , 0.       , 0.       , 0.       , 0.6931472,
        0.       , 0.       , 0.       , 0.       ],
       [0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
        0.       , 0.       , 0.       , 0.       ],
       [0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
        0.       , 0.       , 0.     

In [10]:
adata_Wilson
# batch_key = 'donor_id'
# state_key = 'cell_type'

AnnData object with n_obs × n_vars = 39176 × 2000
    obs: 'donor_id', 'self_reported_ethnicity_ontology_term_id', 'organism_ontology_term_id', 'sample_uuid', 'sample_preservation_method', 'tissue_ontology_term_id', 'development_stage_ontology_term_id', 'suspension_uuid', 'suspension_type', 'library_uuid', 'assay_ontology_term_id', 'mapped_reference_annotation', 'is_primary_data', 'cell_type_ontology_term_id', 'author_cell_type', 'disease_ontology_term_id', 'reported_diseases', 'sex_ontology_term_id', 'nCount_RNA', 'nFeature_RNA', 'percent.mt', 'percent.rpl', 'percent.rps', 'doublet_id', 'nCount_SCT', 'nFeature_SCT', 'seurat_clusters', 'tissue_type', 'cell_type', 'assay', 'disease', 'organism', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid'
    var: 'feature_is_filtered', 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length', 'feature_type', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches

----

# endothelium_subset_TabulaSapiens

In [11]:
# load the adata object
adata_TabulaSapiens = sc.read_h5ad('../data/endothelium_subset_TabulaSapiens/endothelium_subset_TabulaSapiens_final.h5ad')

In [12]:
adata_TabulaSapiens.X[0:10,0:10].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.33613026, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.75878024, 0.        , 0.        , 3.4857001 , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        2.070675  , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 3.3412762 , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        2.3630762 , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.       

In [13]:
adata_TabulaSapiens
# batch_key = 'donor_id'
# state_key = 'cell_type'

AnnData object with n_obs × n_vars = 73195 × 2000
    obs: 'donor_id', 'tissue_in_publication', 'anatomical_position', 'method', 'cdna_plate', 'library_plate', 'notes', 'cdna_well', 'assay_ontology_term_id', 'sample_id', 'replicate', '10X_run', 'ambient_removal', 'donor_method', 'donor_assay', 'donor_tissue', 'donor_tissue_assay', 'cell_type_ontology_term_id', 'compartment', 'broad_cell_class', 'free_annotation', 'manually_annotated', 'published_2022', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'total_counts_ercc', 'pct_counts_ercc', '_scvi_batch', '_scvi_labels', 'scvi_leiden_donorassay_full', 'ethnicity_original', 'scvi_leiden_res05_compartment', 'sample_number', 'organism_ontology_term_id', 'suspension_type', 'tissue_type', 'disease_ontology_term_id', 'is_primary_data', 'tissue_ontology_term_id', 'sex_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'development_stage_ontology_term_id', 'cell_type', 'assay', 'disease', 'organism', 'sex', '

----

# HypoMap_Steuernagel

In [3]:
# load the adata object
adata_Steuernagel = sc.read_h5ad('../data/HypoMap_Steuernagel/HypoMap_Steuernagel_final.h5ad')

In [16]:
adata_Steuernagel.X[0:10,0:10].toarray()

array([[0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
        0.       , 0.       , 0.       , 0.       ],
       [0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
        0.       , 0.       , 0.       , 0.       ],
       [0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
        0.       , 0.       , 0.       , 0.       ],
       [0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
        0.       , 0.       , 0.       , 0.       ],
       [0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
        0.       , 0.       , 0.       , 0.       ],
       [0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
        0.       , 0.       , 0.       , 0.       ],
       [0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
        0.       , 0.       , 0.       , 0.       ],
       [0.       , 0.       , 0.       , 0.       , 1.481257 , 0.       ,
        0.       , 0.       , 0.     

In [17]:
adata_Steuernagel
# batch_key = 'Batch_ID'
# state_key = 'cell_type'

AnnData object with n_obs × n_vars = 384925 × 2000
    obs: 'SRA_ID', 'Sample_ID', 'organism_ontology_term_id', 'donor_id', 'development_stage_ontology_term_id', 'sex_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'disease_ontology_term_id', 'tissue_ontology_term_id', 'cell_type_ontology_term_id', 'assay_ontology_term_id', 'suspension_type', 'Dataset', 'Batch_ID', 'nCount_RNA', 'nFeature_RNA', 'percent_mt', 'C7_named', 'C25_named', 'C66_named', 'C185_named', 'C286_named', 'C465_named', 'Author_Class_Curated', 'Author_CellType', 'Region_summarized', 'is_primary_data', 'tissue_type', 'cell_type', 'assay', 'disease', 'organism', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid'
    var: 'features', 'feature_is_filtered', 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length', 'feature_type', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection'
    uns:

In [4]:
adata_Steuernagel.obs['Batch_ID'].value_counts()

Batch_ID
Anderson10x_batch_1         60756
Kim10x_batch_1              40599
Rupp10x_batch_1             33502
Dowsett10xnuc_batch_1       24759
wen10x_batch_1              17483
wenDropseq_batch_1          16181
CampbellDropseq_batch_1     15641
Moffit10x_batch_3           14958
Morris10x_batch_1           13660
ChenDropseq_batch_1         13329
Morris10x_batch_3           11798
Mousebrainorg10x_batch_2    11747
Dowsett10xnuc_batch_2       11186
Mousebrainorg10x_batch_1     9674
RossiDropseq_batch_1         9292
Moffit10x_batch_2            8892
Affinati10x_batch_1          8477
Mickelsen10x_batch_1         8441
Affinati10x_batch_4          8404
Flynn10x_batch_1             7489
kimDev10x_batch_1            6912
Affinati10x_batch_3          6056
Flynn10x_batch_2             5864
Morris10x_batch_2            5492
CampbellDropseq_batch_2      5248
Moffit10x_batch_1            4185
LeeDropseq_batch_1           2212
RomanovDev10x_batch_1        2152
Affinati10x_batch_2           536
Name:

----

# immune_DominguezConde

In [18]:
adata_DominguezConde = sc.read_h5ad('../data/immune_DominguezConde/immune_DominguezConde_final.h5ad')

In [19]:
adata_DominguezConde.X[0:10,0:10].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.92765963, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.9247127 , 2.455135  , 0.        , 0.9247127 , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.8185749 , 1.5689907 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 2.1640284 ],
       [0.        , 0.        , 0.       

In [20]:
adata_DominguezConde
# batch_key = 'donor_id'
# state_key = 'cell_type'

AnnData object with n_obs × n_vars = 329762 × 2000
    obs: 'donor_id', 'Predicted_labels_CellTypist', 'Majority_voting_CellTypist', 'Majority_voting_CellTypist_high', 'Manually_curated_celltype', 'assay_ontology_term_id', 'cell_type_ontology_term_id', 'development_stage_ontology_term_id', 'disease_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'is_primary_data', 'organism_ontology_term_id', 'sex_ontology_term_id', 'tissue_ontology_term_id', 'suspension_type', 'tissue_type', 'cell_type', 'assay', 'disease', 'organism', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid'
    var: 'gene_symbols', 'feature_is_filtered', 'feature_name', 'feature_reference', 'feature_biotype', 'feature_length', 'feature_type', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection'
    uns: 'cell_type_ontology_term_id_colors', 'citation', 'default_embedding', 'hvg', 'pca', 'schema_reference', 

----

# pancreatic_islet_Hrovatin

In [21]:
adata_Hrovatin = sc.read_h5ad('../data/pancreatic_islet_Hrovatin/pancreatic_islet_Hrovatin_final.h5ad')

In [22]:
adata_Hrovatin.X[0:10,0:10].toarray()

array([[0.        , 2.7333214 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 3.8831608 , 0.        ],
       [0.        , 1.2105592 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 5.2685776 , 0.        ],
       [1.5910618 , 1.9262085 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 3.9092588 , 0.        ],
       [0.        , 2.1863015 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 2.821644  , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 4.93392   , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 5.8095374 , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.81427914, 0.       

In [23]:
adata_Hrovatin
# batch_key = 'batch_integration'
# state_key = 'cell_type'

AnnData object with n_obs × n_vars = 301796 × 2000
    obs: 'batch_integration', 'dataset', 'design', 'cell_cycle_phase', 'ins_high', 'gcg_high', 'sst_high', 'ppy_high', 'cell_filtering', 'strain', 'age', 'cell_type_originalDataset_unified', 'cell_type_originalDataset', 'cell_type_reannotatedIntegrated', 'n_genes', 'mt_frac', 'doublet_score', 'log10_n_counts', 'age_approxDays', 'dataset__design__sample', 'cell_subtype_immune_reannotatedIntegrated', 'cell_subtype_endothelial_reannotatedIntegrated', 'emptyDrops_LogProb_scaled', 'cell_subtype_beta_coarse_reannotatedIntegrated', 'cell_subtype_beta_fine_reannotatedIntegrated', 'GP_1', 'GP_2', 'GP_3', 'GP_4', 'GP_5', 'GP_6', 'GP_7', 'GP_8', 'GP_9', 'GP_10', 'GP_11', 'GP_12', 'GP_13', 'GP_14', 'GP_15', 'GP_16', 'GP_17', 'GP_18', 'GP_19', 'GP_20', 'GP_21', 'GP_22', 'GP_23', 'GP_24', 'GP_25', 'GP_26', 'GP_27', 'assay_ontology_term_id', 'cell_type_ontology_term_id', 'development_stage_ontology_term_id', 'diabetes_model', 'chemical_stress', 'GEO_